package config

type DB struct {
	AccountsCollection                 string
	ActivitiesCollection               string
	AnalyticsCollection                string
	AppealsCollection                  string
	ArtistEventsCollection             string
	ArtistsCollection                  string
	BaitoApplicationsCollection        string
	BaitoCollection                    string
	BaitoWorkerCollection              string
	BlogPostsCollection                string
	BookingsCollection                 string
	BehindTheScenesCollection          string
	CartCollection                     string
	CatalogueCollection                string
	ChatsCollection                    string
	CommentsCollection                 string
	CouponCollection                   string
	CropsCollection                    string
	DateCapsCollection                 string
	EventsCollection                   string
	FarmsCollection                    string
	FundingCollection                  string
	FeedPostsCollection                string
	FilesCollection                    string
	FollowingsCollection               string
	FarmOrdersCollection               string
	HashtagCollection                  string
	HiringCollection                   string
	IdempotencyCollection              string
	ItineraryCollection                string
	JournalCollection                  string
	LikesCollection                    string
	MapsCollection                     string
	MediaCollection                    string
	MenuCollection                     string
	MerchCollection                    string
	MerechatCollection                 string
	MessagesCollection                 string
	ModeratorApplications              string
	NoticesCollection                  string
	NotificationsCollection            string
	NotificationsPreferencesCollection string
	OrderCollection                    string
	PlacesCollection                   string
	ProductCollection                  string
	PurchasedTicketsCollection         string
	RecipeCollection                   string
	RefundsCollection                  string
	ReportsCollection                  string
	ReviewsCollection                  string
	ServiceCollection                  string
	SettingsCollection                 string
	SlotCollection                     string
	SongsCollection                    string
	StripeOrdersCollection             string
	SubscribersCollection              string
	TicketsCollection                  string
	TiersCollection                    string
	TransactionCollection              string
	UserDataCollection                 string
	UserCollection                     string
	VendorCollection                   string
	AlbumsCollection                   string
	PlaylistsCollection                string
	GlobalLedgerCollection             string
}

var Collections = DB{
	AccountsCollection:                 "accounts",
	ActivitiesCollection:               "activities",
	AlbumsCollection:                   "albums",
	AnalyticsCollection:                "analytics",
	AppealsCollection:                  "appeals",
	ArtistEventsCollection:             "artistevents",
	ArtistsCollection:                  "artists",
	BaitoApplicationsCollection:        "baitoapply",
	BaitoCollection:                    "baitos",
	BaitoWorkerCollection:              "baitoworkers",
	BlogPostsCollection:                "blogposts",
	BookingsCollection:                 "bookings",
	BehindTheScenesCollection:          "bts",
	CartCollection:                     "cart",
	CatalogueCollection:                "catalogue",
	ChatsCollection:                    "chats",
	CommentsCollection:                 "comments",
	CouponCollection:                   "coupons",
	CropsCollection:                    "crops",
	DateCapsCollection:                 "date_caps",
	EventsCollection:                   "events",
	FarmsCollection:                    "farms",
	FeedPostsCollection:                "feedposts",
	FilesCollection:                    "files",
	FollowingsCollection:               "followings",
	FarmOrdersCollection:               "forders",
	FundingCollection:                  "funding",
	GlobalLedgerCollection:             "globalledger",
	HashtagCollection:                  "hashtags",
	HiringCollection:                   "hirings",
	IdempotencyCollection:              "idempotency",
	ItineraryCollection:                "itinerary",
	JournalCollection:                  "journals",
	LikesCollection:                    "likes",
	MapsCollection:                     "maps",
	MediaCollection:                    "media",
	MenuCollection:                     "menu",
	MerchCollection:                    "merch",
	MerechatCollection:                 "merechats",
	MessagesCollection:                 "messages",
	ModeratorApplications:              "modapps",
	NoticesCollection:                  "notices",
	NotificationsCollection:            "notifications",
	NotificationsPreferencesCollection: "notificationpreferences",
	OrderCollection:                    "orders",
	PlacesCollection:                   "places",
	PlaylistsCollection:                "playlists",
	ProductCollection:                  "products",
	PurchasedTicketsCollection:         "purticks",
	RecipeCollection:                   "recipes",
	RefundsCollection:                  "refunds",
	ReportsCollection:                  "reports",
	ReviewsCollection:                  "reviews",
	ServiceCollection:                  "service",
	SettingsCollection:                 "settings",
	SlotCollection:                     "slots",
	SongsCollection:                    "songs",
	StripeOrdersCollection:             "stripeorders",
	SubscribersCollection:              "subscribers",
	TicketsCollection:                  "ticks",
	TiersCollection:                    "tiers",
	TransactionCollection:              "transactions",
	UserDataCollection:                 "userdata",
	UserCollection:                     "users",
	VendorCollection:                   "vendors",
}
