package config

type IDField struct {
	AccountId                 string
	ActivityId                string
	AnalyticsId               string
	AppealId                  string
	ArtistEventId             string
	ArtistId                  string
	BaitoApplicationId        string
	BaitoId                   string
	BaitoWorkerId             string
	BandMemberId              string
	BlogPostId                string
	BookingId                 string
	BehindTheSceneId          string
	CartId                    string
	CatalogueId               string
	ChatId                    string
	CommentId                 string
	CouponId                  string
	CropId                    string
	CropsAboutId              string
	DateCapId                 string
	EventId                   string
	FarmId                    string
	FundingId                 string
	FeedPostId                string
	FileId                    string
	FollowingId               string
	FarmOrderId               string
	HashtagId                 string
	HiringId                  string
	IdempotencyId             string
	ItineraryId               string
	JournalId                 string
	LikeId                    string
	LiveId                    string
	MapId                     string
	MediaId                   string
	MenuId                    string
	MerchId                   string
	MerechatId                string
	MessageId                 string
	ModeratorApplicationId    string
	NoticeId                  string
	NotificationId            string
	NotificationsPreferenceId string
	OrderId                   string
	PlaceId                   string
	ProductId                 string
	PurchasedTicketId         string
	RecipeId                  string
	RefundId                  string
	ReportId                  string
	ReviewId                  string
	ServiceId                 string
	SettingId                 string
	SlotId                    string
	SongId                    string
	StripeOrderId             string
	SubscriberId              string
	TicketId                  string
	TierId                    string
	ToolId                    string
	TransactionId             string
	UserDataId                string
	UserId                    string
	VendorId                  string
	VendorAvailabilityId      string
	AlbumId                   string
	PlaylistId                string
	GlobalLedgerId            string
	SeatId                    string
}

var IDFields = IDField{
	GlobalLedgerId:     "_id",
	TransactionId:      "txn_id",
	AccountId:          "_id",
	LiveId:             "liveid",
	VendorId:           "vendorid",
	HiringId:           "hiringid",
	SlotId:             "slotid",
	UserId:             "userid",
	EventId:            "eventid",
	TicketId:           "ticketid",
	SeatId:             "_id",
	ReportId:           "reportid",
	RecipeId:           "recipeid",
	PlaceId:            "placeid",
	NoticeId:           "noticeid",
	ItineraryId:        "itineraryid",
	BaitoWorkerId:      "baitoWorkerId",
	BlogPostId:         "postid",
	FarmId:             "farmid",
	CropId:             "cropid",
	FarmOrderId:        "orderid",
	OrderId:            "id",
	ProductId:          "productid",
	ToolId:             "toolid",
	CommentId:          "commentid",
	MessageId:          "messageid",
	ChatId:             "chatid",
	StripeOrderId:      "stripeorderid",
	BaitoId:            "baitoid",
	BaitoApplicationId: "baitoappid",
	SongId:             "songid",
	ArtistId:           "artistid",
	BandMemberId:       "memberid",
	ArtistEventId:      "eventid",
	FeedPostId:         "postid",
	MerchId:            "merchid",
	MenuId:             "menuid",
	ReviewId:           "reviewid",
	MediaId:            "mediaid",
}
